definitions:
  controlador.request:
    properties:
      activo:
        type: boolean
      altura:
        type: integer
      apellido:
        type: string
      edad:
        type: integer
      email:
        type: string
      fecha_creacion:
        type: string
      nombre:
        type: string
    type: object
  web.Response:
    properties:
      code:
        type: integer
      data: {}
      error:
        type: string
    type: object
info:
  contact:
    name: API Support
    url: https://developers.mercadolibre.com.ar/support
  description: This API Handle MELI Products.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://developers.mercadolibre.com.ar/es_ar/terminos-y-condiciones
  title: MELI Bootcamp API
  version: "1.0"
paths:
  /usuarios:
    get:
      consumes:
      - application/json
      description: get usuarios
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
      summary: List usuarios
      tags:
      - Usuarios
    post:
      consumes:
      - application/json
      description: store usuarios
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: Usuario to store
        in: body
        name: Usuario
        required: true
        schema:
          $ref: '#/definitions/controlador.request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
      summary: Store usuarios
      tags:
      - Usuarios
swagger: "2.0"
