definitions:
  handler.newRequest:
    properties:
      precio:
        type: integer
      stock:
        type: integer
    type: object
  handler.request:
    properties:
      codigo:
        type: string
      color:
        type: string
      fechaCreacion:
        type: string
      nombre:
        type: string
      precio:
        type: integer
      publicado:
        type: boolean
      stock:
        type: integer
    required:
    - codigo
    - color
    - fechaCreacion
    - nombre
    - precio
    - publicado
    - stock
    type: object
  web.Response:
    properties:
      code:
        type: integer
      data: {}
      error:
        type: string
    type: object
info:
  contact:
    name: API Support
    url: https://developers.mercadolibre.com.ar/support
  description: This API Handle MELI Users.
  termsOfService: https://developers.mercadolibre.com.ar/es_ar/terminos_y_condiciones
  title: MELI Bootcamp API
  version: "1.0"
paths:
  /products:
    get:
      consumes:
      - application/json
      description: Este método lista todos los productos existentes en registros
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/web.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.Response'
      summary: GetAll
      tags:
      - Products
    post:
      consumes:
      - application/json
      description: Este método guarda un nuevo producto registros
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: transaction to store
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/handler.request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/web.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.Response'
      summary: Guarda Producto
      tags:
      - Products
  /products/{id}:
    delete:
      description: Este método elimina un producto
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: id of product to delete
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/web.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.Response'
      summary: Elimina producto de los registros
      tags:
      - Products
    patch:
      consumes:
      - application/json
      description: Este método actualiza unproducto con nuevos datos (precio y stock)
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: id of product to update
        in: path
        name: id
        required: true
        type: integer
      - description: product data to update
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/handler.newRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/web.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.Response'
      summary: Actualiza precio y stock de un producto
      tags:
      - Products
    put:
      consumes:
      - application/json
      description: Este método actualiza un producto
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: id of product to update
        in: path
        name: id
        required: true
        type: integer
      - description: product data to update
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/handler.request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/web.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.Response'
      summary: Actualiza Producto
      tags:
      - Products
swagger: "2.0"
