definitions:
  handler.request:
    properties:
      codigo:
        type: string
      color:
        type: string
      fecha_creacion:
        type: string
      nombre:
        type: string
      precio:
        type: number
      publicado:
        type: boolean
      stock:
        type: integer
    type: object
  web.Response:
    properties:
      code:
        type: integer
      data: {}
      error:
        type: string
    type: object
info:
  contact:
    name: API Support
    url: https://developers.mercadolibre.com.ar/support
  description: This is API of meli products
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://developers.mercadolibre.com.ar/es_ar/terminos-y-condiciones
  title: MELI Bootcamp API Christian
  version: "1.0"
paths:
  /productos:
    get:
      consumes:
      - application/json
      description: get products
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: List Products
      tags:
      - Products
    post:
      consumes:
      - application/json
      description: store products
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: Product to store
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/handler.request'
      produces:
      - application/json
      responses: {}
      summary: Store Products
      tags:
      - Products
  /productos/{id}:
    delete:
      consumes:
      - application/json
      description: endpoint to delete a product
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: ProductId to delete
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
      summary: Delete products
      tags:
      - Products
    get:
      consumes:
      - application/json
      description: get product by id
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: ProductId to view
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: List Product by Id
      tags:
      - Products
    patch:
      consumes:
      - application/json
      description: endpoint to update price for a product
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: ProductId to update price
        in: path
        name: id
        required: true
        type: string
      - description: price data for update
        in: body
        name: precio
        schema:
          $ref: '#/definitions/handler.request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
      summary: Update price for the product
      tags:
      - Products
    put:
      consumes:
      - application/json
      description: endpoint to update a product
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: ProductId to update
        in: path
        name: id
        required: true
        type: integer
      - description: Product to update
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/handler.request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
      summary: Update products
      tags:
      - Products
swagger: "2.0"
