definitions:
  handler.request:
    properties:
      activo:
        type: boolean
      altura:
        type: integer
      apellido:
        type: string
      edad:
        type: integer
      email:
        type: string
      fecha_creacion:
        type: string
      nombre:
        type: string
    type: object
  web.Response:
    properties:
      code:
        type: string
      data: {}
      error:
        type: string
    type: object
info:
  contact:
    name: API Support
    url: https://developers.mercadolibre.com.ar/support
  description: This API Handle MELI Products.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://developers.mercadolibre.com.ar/es_ar/terminos-y-condiciones
  title: MELI Bootcamp API
  version: "1.0"
paths:
  /usuarios:
    delete:
      consumes:
      - application/json
      description: eliminar usuario
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: elimina usuario
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/handler.request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
      summary: Eliminar usuario
      tags:
      - Usuarios
    get:
      consumes:
      - application/json
      description: get usuarios
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
      summary: List usuarios
      tags:
      - Usuarios
    patch:
      consumes:
      - application/json
      description: modificar apellido edad usuario
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: modifica apellido edad usuario
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/handler.request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
      summary: Modificar Apellido y Edad usuario
      tags:
      - Usuarios
    post:
      consumes:
      - application/json
      description: registrar usuarios
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: Usuarios to registro
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/handler.request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
      summary: Registrar usuarios
      tags:
      - Usuarios
    put:
      consumes:
      - application/json
      description: modificar usuario
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: modifica usuario
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/handler.request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
      summary: Modificar usuario
      tags:
      - Usuarios
swagger: "2.0"
