definitions:
  handler.request:
    properties:
      codigo_de_transaccion:
        type: integer
      emisor:
        type: string
      fecha_de_transaccion:
        type: string
      moneda:
        type: string
      monto:
        type: number
      receptor:
        type: string
    type: object
  web.Response:
    properties:
      code:
        type: string
      data: {}
      error:
        type: string
    type: object
info:
  contact:
    name: API Support
    url: https://developers.mercadolibre.com.ar/support
  description: This API Handle MELI Products.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://developers.mercadolibre.com.ar/es_ar/terminos-y-condiciones
  title: MELI Bootcamp API
  version: "1.0"
paths:
  /products:
    post:
      consumes:
      - application/json
      description: Create transactions
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: transaction to create
        in: body
        name: transaction
        required: true
        schema:
          $ref: '#/definitions/handler.request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.Response'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/web.Response'
      summary: Create Transactions
      tags:
      - Transactions
  /transactions:
    get:
      consumes:
      - application/json
      description: get transactions
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/web.Response'
      summary: List products
      tags:
      - Products
swagger: "2.0"
