definitions:
  handler.request:
    properties:
      amount:
        type: number
      code:
        type: string
      currency:
        type: string
      date:
        type: string
      issuer:
        type: string
      recipient:
        type: string
    required:
    - amount
    - code
    - currency
    - date
    - issuer
    - recipient
    type: object
  handler.request2:
    properties:
      amount:
        type: number
      code:
        type: string
    required:
    - amount
    - code
    type: object
info:
  contact:
    name: API Support
    url: https://developers.mercadolibre.com.co/support
  description: This API Handle MELI Transactions
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE/2.0.html
  title: MELI Bootcamp API
  version: "1.0"
paths:
  /transaction:
    post:
      consumes:
      - application/json
      description: create transactions
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: Transaction to create
        in: body
        name: transaction
        required: true
        schema:
          $ref: '#/definitions/handler.request'
      produces:
      - application/json
      responses: {}
      summary: Create transaction
      tags:
      - Transactions
  /transaction/{id}:
    delete:
      consumes:
      - application/json
      description: Delete transaction
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: transaction id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: Delete transaction
      tags:
      - Transactions
    get:
      consumes:
      - application/json
      description: get transaction
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: transaction id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: Get transaction
      tags:
      - Transactions
    patch:
      consumes:
      - application/json
      description: Update code and ammount of transaction
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: Transaction to update
        in: body
        name: transaction
        required: true
        schema:
          $ref: '#/definitions/handler.request2'
      - description: transaction id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: Update transaction
      tags:
      - Transactions
    put:
      consumes:
      - application/json
      description: Update transaction
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: Transaction to update
        in: body
        name: transaction
        required: true
        schema:
          $ref: '#/definitions/handler.request'
      - description: transaction id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: Update transaction
      tags:
      - Transactions
  /transactions:
    get:
      consumes:
      - application/json
      description: get transactions
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: List transactions
      tags:
      - Transactions
swagger: "2.0"
