definitions:
  handler.request:
    properties:
      amount:
        type: number
      currency:
        type: string
      reciever:
        type: string
      tranCode:
        type: string
      tranDate:
        type: string
      transmitter:
        type: string
    required:
    - amount
    - currency
    - reciever
    - tranCode
    - tranDate
    - transmitter
    type: object
  web.Response:
    properties:
      code:
        type: string
      data: {}
      error:
        type: string
    type: object
info:
  contact:
    name: API Support
    url: https://developers.mercadolibre.com.ar/support
  description: This API Handle MELI Transactions.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://developers.mercadolibre.com.ar/es_ar/terminos-y-condiciones
  title: MELI BOOTCAMP API
  version: "1.0"
paths:
  /transactions:
    get:
      consumes:
      - application/json
      description: get transactions
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
      tags:
      - Transactions
    post:
      consumes:
      - application/json
      description: store transactions
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: Transaction to store
        in: body
        name: transaction
        required: true
        schema:
          $ref: '#/definitions/handler.request'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
      tags:
      - Transactions
  /transactions/{id}:
    delete:
      consumes:
      - application/json
      description: delete transactions
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: Transaction deleted
        in: body
        name: transaction
        required: true
        schema:
          $ref: '#/definitions/handler.request'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
      tags:
      - Transactions
    patch:
      consumes:
      - application/json
      description: update code and amount transactions
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: Transaction updated
        in: body
        name: transaction
        required: true
        schema:
          $ref: '#/definitions/handler.request'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
      tags:
      - Transactions
    put:
      consumes:
      - application/json
      description: update transactions
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: Transaction updated
        in: body
        name: transaction
        required: true
        schema:
          $ref: '#/definitions/handler.request'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
      tags:
      - Transactions
swagger: "2.0"
