-- MySQL Script generated by MySQL Workbench
-- Fri Aug  5 18:26:27 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema emple_dep
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `emple_dep` ;

-- -----------------------------------------------------
-- Schema emple_dep
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `emple_dep` ;
USE `emple_dep` ;

-- -----------------------------------------------------
-- Table `emple_dep`.`departamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `emple_dep`.`departamentos` ;

CREATE TABLE IF NOT EXISTS `emple_dep`.`departamentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(70) NOT NULL,
  `direccion` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `emple_dep`.`empleados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `emple_dep`.`empleados` ;

CREATE TABLE IF NOT EXISTS `emple_dep`.`empleados` (
  `nro_legajo` INT NOT NULL,
  `dni` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `fech_nac` DATETIME NULL,
  `fech_inco` DATETIME NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `sueldo_net` INT NOT NULL,
  `id_dep` INT NOT NULL,
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC) VISIBLE,
  PRIMARY KEY (`nro_legajo`, `id_dep`),
  INDEX `fk_empleados_departamentos_id_idx` (`id_dep` ASC) VISIBLE,
  CONSTRAINT `fk_empleados_departamentos_id`
    FOREIGN KEY (`id_dep`)
    REFERENCES `emple_dep`.`departamentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
